export * from './profile.entity';
export * from './patient.entity';
export * from './department.entity';
export * from './room.entity';
export * from './appointment.entity';
export * from './examination.entity';
export * from './test-request.entity';
export * from './prescription.entity';
export * from './medical-document.entity';
